.PHONY: clean All

All:
	@echo "----------Building project:[ C___Class_Roster - Debug ]----------"
	@"$(MAKE)" -f  "C___Class_Roster.mk"
clean:
	@echo "----------Cleaning project:[ C___Class_Roster - Debug ]----------"
	@"$(MAKE)" -f  "C___Class_Roster.mk" clean
